DEEPSORT:
  REID_CKPT: "E:/workspace-sts/Gait/GaitGraph-main/detectandsave/deep_sort/deep_sort/deep/checkpoint/ckpt.t7"
  MAX_DIST: 0.1
  MIN_CONFIDENCE: 0.6
  NMS_MAX_OVERLAP: 0.5
  MAX_IOU_DISTANCE: 0.7
  MAX_AGE: 70
  N_INIT: 3
  NN_BUDGET: 1000
  
